[package]
name = "toad"
version = "0.1.0"
edition = "2021"
authors = ["Danny Hammer <hammerapi@gmail.com>"]
license = "MPL-2.0"
description = "Yet another chess engine in Rust"
repository = "https://github.com/dannyhammer/toad"
homepage = "https://github.com/dannyhammer/toad"
keywords = ["chess", "chess engine"]

[dependencies]
anyhow = "1.0.89"
chessie = "1.0.0"
clap = { version = "4.5.18", features = ["derive"] }
num_cpus = "1.16.0"
shlex = "1.3.0"
threadpool = "1.8.1"
