[package]
name = "toad"
version = "0.4.0"
edition = "2021"
authors = ["Danny Hammer <hammerapi@gmail.com>"]
license = "MPL-2.0"
description = "Yet another chess engine in Rust"
repository = "https://github.com/dannyhammer/toad"
homepage = "https://github.com/dannyhammer/toad"
keywords = ["chess", "chess engine"]

[dependencies]
anyhow = "1.0.89"
chessie = "1.1.0"
#chessie = { path = "../chessie/chessie" }
#chessie = { git = "https://github.com/dannyhammer/chessie.git" }
clap = { version = "4.5.18", features = ["derive"] }
#uci-parser = { path = "../uci-parser", features = ["parse-go-perft", "parse-position-kiwipete", "clamp-negatives"] }
uci-parser = { git = "https://github.com/dannyhammer/uci-parser.git", features = ["parse-go-perft", "parse-position-kiwipete", "clamp-negatives"] }
#uci-parser = { version = "0.1.0", features = ["parse-go-perft", "parse-position-kiwipete", "clamp-negatives"] }
